name: flutter_sms_listener
description: A new flutter plugin project.
version: 1.0.0
homepage:

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: br.com.popgas.flutter_sms_listener
        pluginClass: FlutterSmsListenerPlugin